name: Ruby

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: "3.2"
      - name: Install dependencies
        run: gem update --system --no-document && gem install bundler -v 1.17.3 --no-document
      - name: Run
        run: bundle exec rake
